"""Generate a self-contained dark-themed HTML page from knowledge/articles/ JSON files."""

from __future__ import annotations

import json
from pathlib import Path

ARTICLES_DIR = Path(__file__).resolve().parent / "articles"
OUTPUT = Path(__file__).resolve().parent / "index.html"

HEAD = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI Knowledge Base</title>
<style>
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#0d1117;color:#c9d1d9;line-height:1.6}
  .container{max-width:900px;margin:0 auto;padding:24px 16px}
  h1{font-size:1.5rem;color:#58a6ff;margin-bottom:8px}
  .sub{color:#8b949e;font-size:.85rem;margin-bottom:24px}
  .card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:16px;margin-bottom:12px;transition:border-color .2s}
  .card:hover{border-color:#58a6ff}
  .card-title{font-size:1rem;font-weight:600;margin-bottom:6px}
  .card-title a{color:#58a6ff;text-decoration:none}
  .card-title a:hover{text-decoration:underline}
  .card-summary{color:#8b949e;font-size:.9rem;margin-bottom:8px}
  .card-meta{display:flex;flex-wrap:wrap;gap:8px;align-items:center;font-size:.8rem;color:#6e7681}
  .tag{display:inline-block;background:#1f2937;color:#7ee787;padding:2px 8px;border-radius:12px;font-size:.75rem;border:1px solid #238636}
  .score{font-weight:700}
  .score-high{color:#7ee787}
  .score-mid{color:#d2991d}
  .score-low{color:#f85149}
  .badge{display:inline-flex;align-items:center;gap:4px}
  .source-label{color:#8b949e}
  .footer{text-align:center;color:#484f58;font-size:.75rem;padding:32px 0 16px}
  .search-bar{margin-bottom:20px}
  .search-bar input{width:100%;padding:10px 14px;background:#0d1117;border:1px solid #30363d;border-radius:8px;color:#c9d1d9;font-size:.9rem;outline:none}
  .search-bar input:focus{border-color:#58a6ff}
  .stats{margin-bottom:16px;font-size:.8rem;color:#6e7681}
  .stats span{margin-right:16px}
</style>
</head>
<body>
<div class="container">
<h1>AI 技术知识库</h1>
<p class="sub">自动采集 · LLM 分析 · 每日更新</p>
<div class="search-bar"><input type="text" id="search" placeholder="搜索标题、摘要、标签..." oninput="filter()"></div>
<div class="stats" id="stats"></div>
<div id="list"></div>
<div class="footer">Generated by knowledge pipeline · <span id="count"></span> entries</div>
</div>

<script>
var DATA = """

TAIL = """</script>
<script>
  var idx = DATA.length;
  document.getElementById('count').textContent = idx + ' entries';

  function scoreClass(s) {
    if (s >= 8) return 'score-high';
    if (s >= 6) return 'score-mid';
    return 'score-low';
  }

  function render(items) {
    var html = '';
    for (var i = 0; i < items.length; i++) {
      var a = items[i];
      var tags = '';
      if (a.tags && a.tags.length) {
        tags = a.tags.map(function(t){return '<span class="tag">'+escapeHtml(t)+'</span>'}).join(' ');
      }
      var stars = a.stars ? (' ⭐' + a.stars) : '';
      var lang = a.language ? (' [' + escapeHtml(a.language) + ']') : '';
      var reason = a.score_reason ? ('<div class="card-meta" style="margin-top:4px;color:#6e7681">' + escapeHtml(a.score_reason) + '</div>') : '';
      var title = a.source_url
        ? '<a href="' + escapeAttr(a.source_url) + '" target="_blank" rel="noopener">' + escapeHtml(a.title) + '</a>'
        : escapeHtml(a.title);
      html += '<div class="card">' +
        '<div class="card-title">' + title + '</div>' +
        '<div class="card-summary">' + escapeHtml(a.summary) + '</div>' +
        '<div class="card-meta">' +
          '<span class="badge score ' + scoreClass(a.score) + '">' + a.score + '/10</span>' +
          '<span>' + escapeHtml(a.source) + '</span>' +
          '<span>' + stars + '</span>' +
          '<span>' + lang + '</span>' +
        '</div>' +
        (tags ? '<div class="card-meta" style="margin-top:6px">' + tags + '</div>' : '') +
        reason +
      '</div>';
    }
    document.getElementById('list').innerHTML = html;
    document.getElementById('stats').innerHTML =
      '<span>显示 ' + items.length + ' / ' + DATA.length + ' 条</span>';
  }

  function escapeHtml(s) {
    return (s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }
  function escapeAttr(s) {
    return (s||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;');
  }

  function filter() {
    var q = document.getElementById('search').value.toLowerCase().trim();
    if (!q) { render(DATA); return; }
    var words = q.split(/\\s+/);
    var result = [];
    for (var i = 0; i < DATA.length; i++) {
      var a = DATA[i];
      var txt = (a.title+' '+a.summary+' '+(a.tags||[]).join(' ')).toLowerCase();
      var match = true;
      for (var j = 0; j < words.length; j++) {
        if (txt.indexOf(words[j]) === -1) { match = false; break; }
      }
      if (match) result.push(a);
    }
    render(result);
  }

  render(DATA);
</script>
</body>
</html>"""


def _extract_date(filename: str) -> str:
    """Extract YYYY-MM-DD date prefix from filename (e.g., 2026-08-02-...)."""
    parts = filename.split("-", 3)
    if len(parts) >= 3:
        return f"{parts[0]}-{parts[1]}-{parts[2]}"
    return "0000-00-00"


def main() -> None:
    articles = []
    for fp in sorted(ARTICLES_DIR.glob("*.json")):
        try:
            art = json.loads(fp.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue

        articles.append({
            "id": art.get("id", ""),
            "title": art.get("title", ""),
            "source": art.get("source", ""),
            "source_url": art.get("source_url", ""),
            "summary": art.get("summary", ""),
            "score": art.get("score", 0),
            "score_reason": art.get("score_reason", ""),
            "stars": art.get("stars", 0),
            "language": art.get("language", ""),
            "tags": art.get("tags", []),
            "_file": fp.name,
        })

    # Sort descending by filename (date prefix)
    articles.sort(key=lambda a: a["_file"], reverse=True)

    # Remove internal field before embedding
    for a in articles:
        del a["_file"]

    print(f"Loaded {len(articles)} articles")

    data_json = json.dumps(articles, ensure_ascii=False, indent=2)
    html = HEAD + "\n" + data_json + ";\n" + TAIL
    OUTPUT.write_text(html, encoding="utf-8")
    print(f"Written {OUTPUT} ({len(html):,} bytes)")


if __name__ == "__main__":
    main()
